---
name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: SVU
        uses: charlesthomas/github-action-svu@v1.0.6+2.2.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: steps.SVU.outputs.changed
        with:
          distribution: goreleaser
          version: "2.7.0"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
